FROM python:3.12-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt --root-user-action=ignore

COPY ./qlego /app/qlego
COPY ./planqtn_jobs /app/planqtn_jobs
COPY ./planqtn_types /app/planqtn_types

WORKDIR /app

ENV TERM=xterm
ENV PYTHONPATH=/app

ENTRYPOINT ["python", "/app/planqtn_jobs/main.py"]

