FROM python:3.12-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt /app/requirements.txt
COPY planqtn_api/requirements.txt /app/planqtn_api/requirements.txt   

RUN pip install -r requirements.txt -r planqtn_api/requirements.txt --root-user-action=ignore

COPY ./qlego /app/qlego
COPY ./planqtn_api /app/planqtn_api

WORKDIR /app

ENV TERM=xterm
ENV PYTHONPATH=/app

CMD ["python", "/app/planqtn_api/planqtn_server.py"]