FROM python:3.12-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt --root-user-action=ignore

COPY ./qlego /app/qlego

WORKDIR /app

ENV TERM=xterm
ENV PYTHONPATH=/app

CMD ["python", "/app/qlego/"]

