[project]
name = "planqtn"
version = "0.3.0"
authors = [{ name = "Balint Pato", email = "balint@planqtn.com" }]
maintainers = [{ name = "PlanqTN Contributors", email = "planqtn@planqtn.com" }]
description = "PlanqTN is a tensor network quantum error correction library implementation of the quantum LEGO framework."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
]
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = [
  # pin these for galois - otherwise build errors on 3.12
  # "llvmlite>=0.43.0",
  # "numba>=0.61.0",

  "numpy",
  "galois > 0.4",
  "matplotlib",
  "scipy",
  "sympy",
  "pyzx",
  "cotengra==0.7.5",
  "cmaes",
  "attrs",
  "supabase",
]

[project.urls]
Homepage = "https://github.com/planqtn/planqtn"
Issues = "https://github.com/planqtn/planqtn/issues"

[dependency-groups]
dev = [
  "pytest",
  "ipython",
  "pytest-cov",
  "aiohttp",
  # Want to pin to avoid surprise pull request changes
  "black==25.1.0",
  "mypy==1.16.0",
  "pydantic-to-typescript==2.0.0",
  "scipy-stubs",
  "types-tqdm",
  "pylint==3.3.7",
  "flake8",
]
docs = [
  "mkdocs-material",
  "mkdocstrings[python]",
  "mkdocs",
]
api = [
  { include-group = "dev" },
  "fastapi[standard]",
  "uvicorn[standard]",
  "pydantic",
  "pydantic-settings",
  "python-dotenv",
  "requests",
  "httpx",
  "pytest-asyncio",
  "kubernetes",
]
jobs = [
  { include-group = "dev" },
  "fastapi[standard]",
  "uvicorn[standard]",
  "pydantic",
  "pydantic-settings",
  "python-dotenv",
  "requests",
  "kubernetes",
  "supabase",
  "httpx",
  "pytest-asyncio",
  "google-cloud-run",
]

[tool.uv]
default-groups = ["dev"]

[tool.hatch.build.targets.wheel]
packages = ["planqtn"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
