apiVersion: batch/v1
kind: Job
metadata:
  name: monitorthingy2
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: job-monitor
      containers:
        - name: monitor
          image: balopat/planqtn_jobs:bc4a6a7-dirty
          command: ["python", "/app/planqtn_jobs/monitor.py"]
          args:
            - "planqtn-weightenumerator-1748017258982"
            - "f760343a-864c-4689-984b-267d08f2ce62"
            - "49786a54-f785-4649-b059-40d5806e7d2e"
            - "http://host.docker.internal:54321"
            - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
      restartPolicy: Never
  backoffLimit: 0
