#!/bin/bash

export PYTHONPATH=`pwd`:`pwd`/app

find . -type f \( -name '*.py' -o -name 'Dockerfile' -o -name '*.js' -o -name '*.ts' -o -name '*.' \) -not -path "*/app/planqtn_cli/dist/*" | entr -r $@